gcr.io/kaniko-project/executor
gcr.io/google-samples/xtrabackup

docker.io/calico/typha
docker.io/calico/cni
docker.io/calico/node
docker.io/calico/kube-controllers

docker.elastic.co/elasticsearch/elasticsearch
docker.elastic.co/kibana/kibana
docker.elastic.co/logstash/logstash
docker.elastic.co/beats/filebeat
docker.elastic.co/beats/heartbeat
docker.elastic.co/beats/packetbeat
docker.elastic.co/beats/auditbeat
docker.elastic.co/beats/journalbeat
docker.elastic.co/beats/metricbeat
docker.elastic.co/apm/apm-server
docker.elastic.co/app-search/app-search

quay.io/coreos/flannel
quay.io/ceph/ceph
quay.io/cephcsi/cephcsi
quay.io/csiaddons/k8s-sidecar
quay.io/csiaddons/volumereplication-operator
quay.io/prometheus/prometheus
quay.io/prometheus/alertmanager
quay.io/prometheus/pushgateway
quay.io/prometheus/blackbox-exporter
quay.io/prometheus/node-exporter
quay.io/prometheus-operator/prometheus-config-reloader
quay.io/prometheus-operator/prometheus-operator
quay.io/brancz/kube-rbac-proxy
quay.io/cilium/cilium
quay.io/cilium/operator-generic

k8s.gcr.io/etcd
k8s.gcr.io/pause
k8s.gcr.io/kube-proxy
k8s.gcr.io/kube-apiserver
k8s.gcr.io/kube-scheduler
k8s.gcr.io/kube-controller-manager
k8s.gcr.io/coredns/coredns
k8s.gcr.io/dns/k8s-dns-node-cache
k8s.gcr.io/metrics-server/metrics-server
k8s.gcr.io/ingress-nginx/controller
k8s.gcr.io/ingress-nginx/kube-webhook-certgen
k8s.gcr.io/kube-state-metrics/kube-state-metrics
k8s.gcr.io/prometheus-adapter/prometheus-adapter
k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
k8s.gcr.io/sig-storage/csi-node-driver-registrar
k8s.gcr.io/sig-storage/csi-provisioner
k8s.gcr.io/sig-storage/csi-resizer
k8s.gcr.io/sig-storage/csi-snapshotter
k8s.gcr.io/sig-storage/csi-attacher
k8s.gcr.io/sig-storage/nfsplugin
k8s.gcr.io/defaultbackend-amd64