name: sync

on:
  push:
    branches: [ master ]
#   schedule:
#     - cron:  '0 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        . /etc/os-release
        echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y upgrade
        sudo apt-get -y install skopeo
        skopeo --version

    - name: config
      run: |
        bash config.sh

    - name: sync image
      env:
        HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
        HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
      run: |
        bash skopeo.sh
