name: sync

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 */8 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
    - name: sync image
      env:
        HUB_USERNAME: ${{ secrets.HUB_USERNAME }}
        HUB_PASSWORD: ${{ secrets.HUB_PASSWORD }}
      run: |
        bash skopeo.sh
